name: dependencies
description: Dependency injection module for Pokédex App
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  get_it: ^7.2.0
  flutter_mobx: ^2.0.0
  http: ^0.13.5
  equatable: ^2.0.5 
  fpdart: ^1.1.1
  mobx_codegen: ^2.7.0
  mobx: ^2.5.0
dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  
